name: CI

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0 # GitVersion needs the full history and all tags
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@dcb17efb49ec7f20efdebce79cc397a3952c63db # v1.2.0
      with:
        versionSpec: '5.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@dcb17efb49ec7f20efdebce79cc397a3952c63db # v1.2.0
    - name: Setup dotnet
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: |
          8.x
    - name: Build with dotnet
      env:
        VERSION: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
      run: dotnet build --configuration Release -p:Version="$VERSION"
    - name: Test with dotnet
      run: dotnet test --configuration Release --no-build
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: nuget
        path: "**/Kontent.Statiq*.s?nupkg"
    outputs:
      nugetversion: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
      prerelease: ${{ steps.gitversion.outputs.preReleaseTag != '' }}
